In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [2]:
df=pd.read_csv('loan_data.csv')

In [3]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
df.shape

(614, 13)

In [5]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [7]:
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
df['Gender'].value_counts()

Male      489
Female    112
Name: Gender, dtype: int64

In [9]:
df['Gender'].fillna(df['Gender'].mode()[0],inplace=True)

In [10]:
df['Gender'].isna().sum()

0

In [11]:
df['Married'].unique()

array(['No', 'Yes', nan], dtype=object)

In [12]:
df['Married'].value_counts()

Yes    398
No     213
Name: Married, dtype: int64

In [13]:
df['Married'].fillna(df['Married'].mode()[0],inplace=True)

In [14]:
df['Married'].isna().sum()

0

In [15]:
df['Dependents'].value_counts()

0     345
1     102
2     101
3+     51
Name: Dependents, dtype: int64

In [16]:
#fill nulla with sklearn
from sklearn.impute import SimpleImputer
mean_imputer = SimpleImputer(strategy='mean')
median_imputer = SimpleImputer(strategy='median')
mode_imputer = SimpleImputer(strategy='most_frequent')

In [17]:
df['Dependents']=mode_imputer.fit_transform(df[['Dependents']])

In [18]:
df['Dependents'].isna().sum()

0

In [19]:
df['Self_Employed'].value_counts()

No     500
Yes     82
Name: Self_Employed, dtype: int64

In [20]:
df['Self_Employed']=mode_imputer.fit_transform(df[['Self_Employed']])

In [21]:
df['Self_Employed'].isna().sum()

0

In [22]:
df['LoanAmount'].describe()

count    592.000000
mean     146.412162
std       85.587325
min        9.000000
25%      100.000000
50%      128.000000
75%      168.000000
max      700.000000
Name: LoanAmount, dtype: float64

In [23]:
len(df[df['LoanAmount']>200])

80

In [24]:
df['LoanAmount']=mean_imputer.fit_transform(df[['LoanAmount']])

In [25]:
df['LoanAmount'].isna().sum()

0

In [26]:
#fill null values with KNN
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=5)

In [27]:
df['Loan_Amount_Term']=imputer.fit_transform(df[['Loan_Amount_Term']])

In [28]:
df['Loan_Amount_Term'].isna().sum()

0

In [29]:
df['Credit_History'].value_counts()

1.0    475
0.0     89
Name: Credit_History, dtype: int64

In [30]:
df['Credit_History']=imputer.fit_transform(df[['Credit_History']])

In [31]:
df['Credit_History'].isna().sum()

0

In [32]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [33]:
#data split to train and test

In [34]:
#convert category to numerical
from sklearn.preprocessing import LabelEncoder
df=pd.get_dummies(df,columns=['Loan_Status'],drop_first=True)

In [35]:
df.head(3)

Loan_ID Gender Married Dependents Education Self_Employed  \
0  LP001002   Male      No          0  Graduate            No   
1  LP001003   Male     Yes          1  Graduate            No   
2  LP001005   Male     Yes          0  Graduate           Yes   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   

   Credit_History Property_Area  Loan_Status_Y  
0             1.0         Urban              1  
1             1.0         Rural              0  
2             1.0         Urban              1

In [39]:
x = df.drop(columns=['Loan_ID','Gender','Married','Dependents','Education','Self_Employed','Property_Area','Loan_Status_Y'], axis=1)
y = df['Loan_Status_Y']

In [40]:
x.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History  
0             1.0  
1             1.0  
2             1.0  
3             1.0  
4             1.0

In [41]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Loan_Status_Y, dtype: uint8

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,shuffle=True)

In [43]:
X_train.shape,Y_train.shape

((491, 5), (491,))

In [44]:
X_test.shape,Y_test.shape

((123, 5), (123,))

In [45]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [46]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=uint8)

In [47]:
np.sum(y_pred)

109

In [50]:
Y_test.values

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1], dtype=uint8)

In [51]:
np.sum(Y_test)

85

In [53]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

r2_score(Y_test,y_pred)

0.009907120743034237

In [54]:
# with KNN
from sklearn.neighbors import KNeighborsRegressor

knn_model = KNeighborsRegressor(n_neighbors=4)
knn_model.fit(X_train,Y_train)
y_pred = knn_model.predict(X_test)

In [55]:
y_pred

array([0.75, 1.  , 0.5 , 0.5 , 0.75, 1.  , 0.75, 1.  , 0.25, 1.  , 0.25,
       0.5 , 0.75, 0.75, 0.5 , 1.  , 0.75, 0.75, 0.5 , 1.  , 1.  , 0.5 ,
       1.  , 1.  , 0.75, 1.  , 1.  , 0.75, 0.75, 0.75, 1.  , 0.75, 0.75,
       1.  , 0.5 , 0.75, 1.  , 1.  , 1.  , 0.75, 0.75, 0.75, 0.75, 0.5 ,
       0.75, 1.  , 1.  , 0.75, 1.  , 0.75, 0.75, 0.25, 0.5 , 1.  , 1.  ,
       1.  , 0.75, 1.  , 0.75, 1.  , 1.  , 0.5 , 0.75, 0.5 , 0.75, 1.  ,
       0.75, 0.75, 1.  , 0.  , 0.75, 0.5 , 1.  , 1.  , 0.25, 1.  , 1.  ,
       0.75, 0.5 , 1.  , 0.75, 0.75, 0.75, 0.75, 0.75, 1.  , 0.75, 0.75,
       0.75, 1.  , 1.  , 0.5 , 0.75, 0.25, 0.5 , 0.75, 0.75, 1.  , 0.25,
       0.25, 1.  , 0.75, 0.75, 1.  , 1.  , 0.75, 0.25, 0.75, 0.5 , 0.75,
       1.  , 0.5 , 0.5 , 0.75, 1.  , 0.5 , 1.  , 0.5 , 0.5 , 0.75, 0.75,
       0.5 , 0.75])

In [57]:
Y_test.values

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1], dtype=uint8)

In [58]:
np.sum(y_pred)

92.5

In [59]:
np.sum(Y_test)

85